
import javax.swing.ImageIcon;
import javax.swing.JButton;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author macstudent
 */
public class TicTac extends javax.swing.JFrame {
char board[][]={{'R' ,'R', 'R'},
        {'R', 'R', 'R'},
            {'R', 'R', 'R'}};
    boolean player = true; // 'x'
    ImageIcon X = new ImageIcon(getClass().getResource("X.png"));
    ImageIcon O = new ImageIcon(getClass().getResource("O.png"));
    
    
    /**
     * Creates new form TicTac
     */
    public TicTac() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bttn01 = new javax.swing.JButton();
        bttn00 = new javax.swing.JButton();
        bttn02 = new javax.swing.JButton();
        bttn10 = new javax.swing.JButton();
        bttn11 = new javax.swing.JButton();
        bttn12 = new javax.swing.JButton();
        bttn21 = new javax.swing.JButton();
        bttn20 = new javax.swing.JButton();
        bttn22 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Tic Tac");

        bttn01.setText("jButton1");
        bttn01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn01ActionPerformed(evt);
            }
        });

        bttn00.setText("jButton1");
        bttn00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn00ActionPerformed(evt);
            }
        });

        bttn02.setText("jButton1");
        bttn02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn02ActionPerformed(evt);
            }
        });

        bttn10.setText("jButton1");
        bttn10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn10ActionPerformed(evt);
            }
        });

        bttn11.setText("jButton1");
        bttn11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn11ActionPerformed(evt);
            }
        });

        bttn12.setText("jButton1");
        bttn12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn12ActionPerformed(evt);
            }
        });

        bttn21.setText("jButton1");
        bttn21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn21ActionPerformed(evt);
            }
        });

        bttn20.setText("jButton1");
        bttn20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn20ActionPerformed(evt);
            }
        });

        bttn22.setText("jButton1");
        bttn22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn22ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bttn00, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn01, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(bttn02, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn20, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttn21, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bttn10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bttn11, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttn12, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bttn22, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(153, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn02)
                    .addComponent(bttn01)
                    .addComponent(bttn00))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn10)
                    .addComponent(bttn11)
                    .addComponent(bttn12))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bttn21)
                    .addComponent(bttn22)
                    .addComponent(bttn20))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bttn00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn00ActionPerformed
        // TODO add your handling code here:
        select(this.bttn00, 00);
    }//GEN-LAST:event_bttn00ActionPerformed

    private void bttn01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn01ActionPerformed
        // TODO add your handling code here:
        select(this.bttn01, 01);
    }//GEN-LAST:event_bttn01ActionPerformed

    private void bttn02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn02ActionPerformed
        // TODO add your handling code here:
        select(this.bttn02, 02);
    }//GEN-LAST:event_bttn02ActionPerformed

    private void bttn10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn10ActionPerformed
        // TODO add your handling code here:
        select(this.bttn10, 10);
    }//GEN-LAST:event_bttn10ActionPerformed

    private void bttn11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn11ActionPerformed
        // TODO add your handling code here:
        select(this.bttn11, 11);
    }//GEN-LAST:event_bttn11ActionPerformed

    private void bttn12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn12ActionPerformed
        // TODO add your handling code here:
        select(this.bttn12, 12);
    }//GEN-LAST:event_bttn12ActionPerformed

    private void bttn20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn20ActionPerformed
        // TODO add your handling code here:
        select(this.bttn20, 20);
    }//GEN-LAST:event_bttn20ActionPerformed

    private void bttn21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn21ActionPerformed
        // TODO add your handling code here:
        select(this.bttn21, 21);
    }//GEN-LAST:event_bttn21ActionPerformed

    private void bttn22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn22ActionPerformed
        // TODO add your handling code here:
        select(this.bttn22, 22);
    }//GEN-LAST:event_bttn22ActionPerformed
public void select(JButton bttn,int cell){
        int row = cell/10;
        int col = cell % 10;
        
        if (player){
            board[row][col] ='X';
           bttn.setIcon(X);
        }else{
        board[row][col] ='O'; 
        bttn.setIcon(O);
        }
        player = !player;
        bttn.setEnabled(false);
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TicTac.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TicTac().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttn00;
    private javax.swing.JButton bttn01;
    private javax.swing.JButton bttn02;
    private javax.swing.JButton bttn10;
    private javax.swing.JButton bttn11;
    private javax.swing.JButton bttn12;
    private javax.swing.JButton bttn20;
    private javax.swing.JButton bttn21;
    private javax.swing.JButton bttn22;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
